import { useEffect, useState } from 'react'
import { ensurePublicPaper, getAdminPapers, removePaper } from '../../firebase/content'
import { getFreePdfUrl, removePdf, syncPdfPermission } from '../../firebase/storage'
import PastPaperForm from './PastPaperForm'

export default function PastPapersManager({ user }) {
  const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const [error, setError] = useState('')
  const syncPublicPaper = async (item) => { const access = item.access || 'premium'; try { await syncPdfPermission(item.filePath, access, item.published !== false) } catch { /* legacy object metadata may be unreachable; public metadata still gets published below */ } let freeDownloadUrl; if (access === 'free') { try { freeDownloadUrl = await getFreePdfUrl(item.filePath) } catch { freeDownloadUrl = undefined } } try { await ensurePublicPaper(item, freeDownloadUrl) } catch { /* keep loading the rest of the list even if one paper's public mirror fails */ } }
  const load = async () => { try { const data = await getAdminPapers(); await Promise.all(data.map(syncPublicPaper)); setItems(data); setError('') } catch { setError('Unable to load past papers. Refresh and try again.') } }
  useEffect(() => { let active = true; getAdminPapers().then((data) => Promise.all(data.map(syncPublicPaper)).then(() => { if (active) setItems(data) })).catch(() => { if (active) setError('Unable to load past papers. Refresh and try again.') }); return () => { active = false } }, [])
  const remove = async (item) => { if (!window.confirm(`Delete ${item.title}?`)) return; try { await removePaper(item.id); await removePdf(item.filePath); load() } catch { setError('The past paper could not be deleted.') } }
  return <section className="admin-manager"><div className="admin-manager-heading"><div><span className="admin-kicker">Premium Sources</span><h2>Past papers</h2></div><span>{items.length} resources</span></div>{error && <p className="admin-error">{error}</p>}<PastPaperForm key={editing?.id || 'new'} user={user} editing={editing} onSaved={() => { setEditing(null); load() }} onCancel={() => setEditing(null)} /><div className="admin-records">{items.length ? items.map((item) => <article key={item.id}><div><strong>{item.title}</strong><span>{item.pathway} · {item.subject}</span><small>{item.fileName}</small></div><div className="admin-record-actions">{item.fileUrl && <a href={item.fileUrl} target="_blank" rel="noreferrer">View</a>}<button type="button" onClick={() => setEditing(item)}>Edit</button><button type="button" onClick={() => remove(item)}>Delete</button></div></article>) : <p className="admin-empty">No past papers have been uploaded yet.</p>}</div></section>
}
