import { useState } from 'react'
import { createPaper, updatePaper } from '../../firebase/content'
import { removePdf, uploadPdf } from '../../firebase/storage'
import { SUPPORTED_PATHWAYS, validatePaper } from '../../firebase/validation'

const empty = { title: '', pathway: SUPPORTED_PATHWAYS[0], subject: '', access: 'premium', published: true }
export default function PastPaperForm({ user, editing, onSaved, onCancel }) {
  const [values, setValues] = useState(editing ? { ...empty, ...editing } : empty); const [file, setFile] = useState(null); const [errors, setErrors] = useState({}); const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false)
  const submit = async (event) => { event.preventDefault(); const nextErrors = validatePaper(values, file); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; setBusy(true); let uploadedPath; try { const resourceId = editing?.id || crypto.randomUUID(); const details = file ? await uploadPdf(file, resourceId, values.access, setProgress) : { filePath: values.filePath, fileName: values.fileName, fileSize: values.fileSize }; uploadedPath = file ? details.filePath : undefined; if (editing) await updatePaper(editing.id, values, user.uid, editing.version || 1, details); else await createPaper(values, user.uid, details.filePath, details.fileName, details.fileSize); setValues(empty); setFile(null); setProgress(0); onSaved() } catch (uploadError) { if (uploadedPath && !editing) await removePdf(uploadedPath).catch(() => {}) ; setErrors({ form: uploadError.code === 'storage/no-default-bucket' ? 'Firebase Storage is not initialized. Open the Firebase Storage console and click Get started.' : 'The PDF could not be saved. Check Firebase Storage and Firestore rules, then try again.' }) } finally { setBusy(false) } }
  return <form className="admin-form" onSubmit={submit}><h3>{editing ? 'Edit past paper' : 'Upload past paper'}</h3><label>Title<input value={values.title} onChange={(event) => setValues({ ...values, title: event.target.value })} />{errors.title && <small>{errors.title}</small>}</label><label>Pathway<select value={values.pathway} onChange={(event) => setValues({ ...values, pathway: event.target.value })}>{SUPPORTED_PATHWAYS.map((pathway) => <option key={pathway}>{pathway}</option>)}</select>{errors.pathway && <small>{errors.pathway}</small>}</label><label>Subject<input value={values.subject} onChange={(event) => setValues({ ...values, subject: event.target.value })} />{errors.subject && <small>{errors.subject}</small>}</label><fieldset className="admin-access"><legend>Paper permission</legend><label><input type="radio" name="access" value="free" checked={values.access === 'free'} onChange={(event) => setValues({ ...values, access: event.target.value })} /> Free, preview and download</label><label><input type="radio" name="access" value="premium" checked={values.access === 'premium'} onChange={(event) => setValues({ ...values, access: event.target.value })} /> Premium, blurred preview only</label>{errors.access && <small>{errors.access}</small>}</fieldset><label>PDF file<input type="file" accept="application/pdf,.pdf" onChange={(event) => setFile(event.target.files?.[0] || null)} />{errors.file && <small>{errors.file}</small>}</label><label className="admin-check"><input type="checkbox" checked={values.published} onChange={(event) => setValues({ ...values, published: event.target.checked })} /> Publish on website</label>{busy && <progress max="100" value={progress}>{progress}%</progress>}{errors.form && <p className="admin-error">{errors.form}</p>}<div className="admin-form-actions"><button className="orange-button" disabled={busy}>{busy ? `Saving ${progress}%` : 'Save past paper'}</button>{editing && <button className="outline-button" type="button" onClick={onCancel}>Cancel</button>}</div></form>
}
